# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Talita Sara
tagline:             'a menina mais linda do mundo'
description:         'Tudo aqui é para a menina mais linda do mundo'
url:                 http://sifiyoke.github.io
baseurl:             '' 
paginate:            5

# About/contact
author:
  name:              OmeGa
  url:               https://github.com/alpha-omega
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Excerpt Separator
excerpt_separator: "<!--more-->"
